livebooking/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from livebooking import views

urlpatterns = [
                  url(r'^admin/', admin.site.urls),
                  url(r'^accounts/', include('allauth.urls')),
                  url(r'^', include('services.urls')),
                  url(r'^$', views.index, name='index'),

              ] \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.conf.urls import url

from . import views

app_name = 'services'
urlpatterns = [
    url(r"^search/$", views.search_result, name="search_result"),
    url(r"^professional/$", views.professional, name="professional"),
]

users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # url(r"^signup/$", views.signup, name="account_signup"),
]

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block title %}
            livebook
        {% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "assets/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{% static "css/style.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>


<body>
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">LB</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'index' %}">Главная</a></li>
                <li><a href="#">Специалисты</a></li>
                <li><a href="#">Новости</a></li>
                <li><a href="#">Контакты</a></li>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>


{% block content %}
{% endblock content %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static "js/jquery-3.2.1.js" %}"><\/script>')</script>
<script src="{% static "assets/bootstrap/js/bootstrap.min.js" %}"></script>
</body>
</html>

templates/main/index.html
{% extends 'main/base.html' %}
{% load pinax_news_tags %}


{% block content %}

    {% include 'services/search_box.html' %}

    <div class="container">
        <div class="row">
            {% for item in service_categories %}
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 text-center">
                    <a href="{% url 'services:search_result' %}?search_text={{ item.name }}" class="thumbnail">
                        <img style="position: relative" class="center-block"
                             src="http://lorempixel.com/458/240?rand={{ item.id }}" alt="Image">
                        <p>
                        <h2>{{ item.name }}</h2></p>
                    </a>
                </div>

            {% endfor %}
        </div> <!-- end row -->
    </div> <!-- end container -->

    <div class="row bckgr-gray" id="news">
        {% press_release 0 as press_release1 %}
        {% press_release 1 as press_release2 %}
        {% press_release 2 as press_release3 %}
        <div class="container">
            <h2 class="text-center">Новости</h2>

            <div class="col-sm-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h4><b>{{ press_release1.title }}</b></h4>
                        <p>{{ press_release1.description }}</p>
                    </div>
                </div>
            </div> <!-- end col-sm-6 -->

            <div class="col-sm-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h4><b>{{ press_release2.title }}</b></h4>
                        <p>{{ press_release2.description }}</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <h4><b>{{ press_release3.title }}</b></h4>
                        <p>{{ press_release3.description }}</p>
                    </div>
                </div>
            </div>
        </div> <!-- end container -->
    </div> <!-- end row -->


    <div class="row" id="partners">

        <div class="container text-center">
            <h3>Специалисты</h3>

            <div class="col-xs-6 col-sm-2 col-sm-offset-1 col-md-2 col-lg-2 ">
                <div class="thumbnail">
                    <img src="http://placehold.it/100"/>
                </div>
            </div>

            <div class="col-xs-6 col-sm-2 col-md-2 col-lg-2">
                <div class="thumbnail">
                    <img src="http://placehold.it/100"/>
                </div>
            </div>

            <div class="col-xs-6 col-sm-2 col-md-2 col-lg-2">
                <div class="thumbnail">
                    <img src="http://placehold.it/100"/>
                </div>
            </div>

            <div class="col-xs-6 col-sm-2 col-md-2 col-lg-2">
                <div class="thumbnail">
                    <img src="http://placehold.it/100"/>
                </div>
            </div>

            <div class="col-xs-6 col-sm-2 col-md-2 col-lg-2">
                <div class="thumbnail">
                    <img src="http://placehold.it/100"/>
                </div>
            </div>


        </div> <!-- end container -->
    </div><!--end partners-->
{% endblock content %}